version: '3.7'
services:
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami1.docker.localhost`)"
