version: '3.7'
services:
    reverse-proxy:
        # The official v2.0 Traefik docker image
        image: traefik:2.1
        restart: always
        # Enables the web UI and tells Traefik to listen to docker
        ports:
          # The HTTP port
          - "80:80"
          # The Web UI (enabled by --api.insecure=true)
          - "8080:8080"
        volumes:
          # So that Traefik can listen to the Docker events
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik.yml:/etc/traefik/traefik.yml:ro
